import React from 'react'
import "./About.css"
import clock from "../assets/logo/pngegg.png"
import { useEffect } from 'react'
function About(props) {
  
    useEffect(() => {
        const handleScroll = () => {
          const scrollPos = window.scrollY;
          const head = document.querySelector(".about_head");
          const headPos = head?.offsetHeight || 0;
    
          if (scrollPos > headPos + 30) {
            head.style.top = 0 + 'px';
            head.style.opacity = 1;
          } else {
            head.style.top = 60 + 'px';
            head.style.opacity = 0;
          }
        };
    
        window.addEventListener("scroll", handleScroll);
    
        return () => {
          window.removeEventListener("scroll", handleScroll);
        };
      }, []);
  return (
    <>
        <div className="about" id='2'>
            <div className={`about_container ${props.mode ? '' : 'l'}`} >
            <div className={` about_head ${props.mode ? '' : 'light'}`} >
                <h1>Unleash your potential!</h1>
                <h2>Boost productivity</h2>
            </div>
                <div className="about_content">
                <div className="card">
            <div className="card__container">
                <article className="card__article">
                    <div className="card__data">
                        <img src='https://clockify.me/assets/images/clockify-logo.png' alt="card img" className="card__img"/>
    
                        <h1 className="card__title">Boost Your Productivity</h1>
                        <p className="card__description"> Track your web time and take control of your online activities with our powerful Productivity Tracker Chrome extension. Gain valuable insights, improve time management, and make informed decisions about how you allocate your time.</p>
                    </div>
    
                    <div className="card__shapes">
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                    </div>
                </article>
    
                <article className="card__article">
                    <div className="card__data">
                        <img src={clock} alt="card img" className="card__img"/>
    
                        <h1 className="card__title">Privacy-Focused and Secure!</h1>
                        <p className="card__description">Our recently launched Productivity Tracker Chrome extension prioritizes your privacy. Rest assured, our privacy-focused productivity tracker never collects any user data, ensuring complete anonymity. All information generated by the extension is securely stored in your browser's local storage.</p>
                    </div>
    
                    <div className="card__shapes">
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                    </div>
                </article>
    
                <article className="card__article">
                    <div className="card__data">
                        <img src="https://trackingtime.co/logo/trackingtime-logo.png" alt="card img" className="card__img"/>
    
                        <h1 className="card__title"> Constantly Evolving for Enhanced Productivity!</h1>
                        <p className="card__description">Stay ahead of the game with our Productivity Tracker Chrome extension's continuous development and upcoming features. Enjoy advanced website-specific tracking, a convenient task management timer, seamless integration of a to-do list, and customizable productivity goals.</p>
                    </div>
    
                    <div className="card__shapes">
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                        <span className="card__shape"></span>
                    </div>
                </article>
            </div>
        </div>
                    
                   
                </div>
            </div>
        </div>
    </>
  )
}

export default About